### ISSUE TITLE
"Error while using brush function."

### ISSUE THREAD

**Issue by diogoedl** [louismullie/coreslicer#1]
In coreslicer.com, when I try using the automatic segmentation tool, it gives me an error:
"Error while using brush function."

I have tried with two different studies and in different slices of the studies. 

Manual segmentation works fine.

**Comment by StewartMW1234** [comment]
Hello. 
I have the exact same problem. Tried to install NVP and bower but no success. I would greatly appreciate any help to get the automation to work.

**Comment by louismullie** [comment]
Hi to both of you,

Thank you for reporting this issue, which should now have been fixed. Kindly awaiting your confirmation to close.

**Comment by diogoedl** [comment]
Hi, Louis,
Indeed I have managed to use autosegmentation in the coreslicer.com installation.
Thank you very much and congratulations on the awesome tool!
